export const lagerListe = [
  { title: "Fritz Cola", name: "fritz_cola" },
  { title: "Fritz Lemon", name: "fritz_lemon" },
  { title: "Fritz Rababer", name: "fritz_rababer" },
  { title: "Hyldeblomst", name: "hyldeblomst" },
  { title: "Tranebær", name: "tranebær" },
  { title: "Solbær", name: "solbær" },
  { title: "Faxe Kondi", name: "faxe_kondi" },
  { title: "Faxe Kondi Free", name: "faxe_kondi_free" },
  { title: "Pepsi Max", name: "pepsi_max" },
  { title: "Coca-Cola", name: "coca_cola" },
  { title: "Maté Maté", name: "mate_mate" },
  { title: "Ginger Beer", name: "ginger_beer" },
  { title: "Danskvand", name: "danskvand" },
  { title: "Danskvand citrus", name: "danskvand_citrus" },
  { title: "Vand", name: "vand" },
  { title: "Æble juice", name: "æble_juice" },
  { title: "Appelsin juice", name: "appelsin_juice" },
];
